export interface SpectrumPair {
  left: string;
  right: string;
  category: string;
  leftHe: string;
  rightHe: string;
  categoryHe: string;
}

type Pair4 = [string, string, string, string];

const cat = (category: string, categoryHe: string, pairs: Pair4[]): SpectrumPair[] =>
  pairs.map(([left, right, leftHe, rightHe]) => ({ left, right, category, leftHe, rightHe, categoryHe }));

export const SPECTRA_BY_CATEGORY: Record<string, SpectrumPair[]> = {
  "Emotions": cat("Emotions", "רגשות", [
    ["Happy", "Sad", "שמח", "עצוב"],
    ["Love", "Hate", "אהבה", "שנאה"],
    ["Hope", "Fear", "תקווה", "פחד"],
    ["Calm", "Anxious", "רגוע", "חרדתי"],
    ["Proud", "Shameful", "גאה", "מתבייש"],
    ["Trust", "Doubt", "אמון", "ספק"],
    ["Rushed", "Relaxed", "ממהר", "נינוח"],
    ["Boring", "Exciting", "משעמם", "מרגש"],
    ["Nice", "Mean", "נחמד", "מרושע"],
    ["Cute", "Scary", "חמוד", "מפחיד"],
    ["Joyful", "Melancholic", "עליז", "מלנכולי"],
    ["Confident", "Insecure", "בטוח בעצמי", "חסר ביטחון"],
    ["Brave", "Cowardly", "אמיץ", "פחדן"],
    ["Curious", "Apathetic", "סקרן", "אדיש"],
    ["Optimistic", "Pessimistic", "אופטימי", "פסימי"],
    ["Grateful", "Entitled", "אסיר תודה", "מפונק"],
    ["Patient", "Impatient", "סבלני", "חסר סבלנות"],
    ["Gentle", "Harsh", "עדין", "קשוח"],
    ["Tender", "Tough", "ענוג", "קשוח"],
    ["Warm", "Distant", "חם", "מרוחק"],
    ["Empathetic", "Detached", "אמפתי", "מנותק"],
    ["Passionate", "Indifferent", "נלהב", "צונן"],
    ["Innocent", "Cynical", "תמים", "ציני"],
    ["Nostalgic", "Forward-looking", "נוסטלגי", "פונה קדימה"],
    ["Stressed", "Carefree", "לחוץ", "חסר דאגות"],
    ["Frantic", "Zen", "היסטרי", "שלו"],
    ["Lonely", "Connected", "בודד", "מחובר"],
    ["Moody", "Even-tempered", "הפכפך", "יציב"],
    ["Ecstatic", "Gloomy", "מרוגש", "קודר"],
    ["Reckless", "Cautious", "פזיז", "זהיר"],
  ]),
  "Food & Drink": cat("Food & Drink", "אוכל ושתייה", [
    ["Sweet", "Sour", "מתוק", "חמוץ"],
    ["Healthy", "Junk", "בריא", "ג'אנק"],
    ["Pizza", "Sushi", "פיצה", "סושי"],
    ["Tea", "Coffee", "תה", "קפה"],
    ["Salty", "Spicy", "מלוח", "חריף"],
    ["Fresh", "Processed", "טרי", "מעובד"],
    ["Homemade", "Takeout", "ביתי", "טייק אווי"],
    ["Soda", "Water", "סודה", "מים"],
    ["Dessert", "Appetizer", "קינוח", "מנה ראשונה"],
    ["Wine", "Beer", "יין", "בירה"],
    ["Croissant", "Bagel", "קרואסון", "בייגל"],
    ["Burger", "Salad", "המבורגר", "סלט"],
    ["Chocolate", "Fruit", "שוקולד", "פירות"],
    ["Pancakes", "Omelette", "פנקייק", "חביתה"],
    ["Creamy", "Crunchy", "קרמי", "פריך"],
    ["Comfort food", "Fine dining", "אוכל מנחם", "אוכל יוקרתי"],
    ["Street food", "Restaurant", "אוכל רחוב", "מסעדה"],
    ["Cooking", "Baking", "בישול", "אפייה"],
    ["Grilled", "Fried", "על האש", "מטוגן"],
    ["Whole milk", "Skim milk", "חלב מלא", "חלב דל"],
    ["Bacon", "Tofu", "בייקון", "טופו"],
    ["Ice cream", "Frozen yogurt", "גלידה", "יוגורט קפוא"],
    ["Sushi", "Burrito", "סושי", "בוריטו"],
    ["Soup", "Sandwich", "מרק", "סנדוויץ'"],
    ["Popcorn", "Nachos", "פופקורן", "נאצ'וס"],
    ["Mint", "Cinnamon", "מנטה", "קינמון"],
    ["Ketchup", "Mustard", "קטשופ", "חרדל"],
    ["Rice", "Pasta", "אורז", "פסטה"],
    ["Smoothie", "Milkshake", "שייק", "מילקשייק"],
    ["Brunch", "Midnight snack", "בראנץ'", "חטיף חצות"],
  ]),
  "Nature & Weather": cat("Nature & Weather", "טבע ומזג אוויר", [
    ["Hot", "Cold", "חם", "קר"],
    ["Light", "Dark", "בהיר", "כהה"],
    ["City", "Countryside", "עיר", "כפר"],
    ["Summer", "Winter", "קיץ", "חורף"],
    ["Beach", "Mountains", "חוף", "הרים"],
    ["Water", "Land", "מים", "יבשה"],
    ["Inside", "Outside", "בפנים", "בחוץ"],
    ["Wet", "Dry", "רטוב", "יבש"],
    ["Rural", "Urban", "כפרי", "עירוני"],
    ["Loud", "Quiet", "רועש", "שקט"],
    ["Silence", "Noise", "דממה", "רעש"],
    ["Ocean", "Desert", "אוקיינוס", "מדבר"],
    ["Forest", "Meadow", "יער", "אחו"],
    ["Sunrise", "Sunset", "זריחה", "שקיעה"],
    ["Thunder", "Breeze", "רעם", "בריזה"],
    ["Snow", "Rain", "שלג", "גשם"],
    ["Fire", "Ice", "אש", "קרח"],
    ["Spring", "Autumn", "אביב", "סתיו"],
    ["River", "Lake", "נהר", "אגם"],
    ["Jungle", "Tundra", "ג'ונגל", "טונדרה"],
    ["Storm", "Clear sky", "סערה", "שמיים בהירים"],
    ["Volcano", "Glacier", "הר געש", "קרחון"],
    ["Wild", "Tame", "פראי", "מאולף"],
    ["Island", "Coast", "אי", "קו חוף"],
    ["Cave", "Mountain peak", "מערה", "פסגת הר"],
    ["Shade", "Sunlight", "צל", "אור שמש"],
    ["Polluted", "Pristine", "מזוהם", "בתולי"],
    ["Lakeside", "Waterfall", "שפת אגם", "מפל"],
    ["Garden", "Wilderness", "גן", "טבע פראי"],
    ["Tropical", "Arctic", "טרופי", "ארקטי"],
  ]),
  "Animals": cat("Animals", "חיות", [
    ["Cat", "Dog", "חתול", "כלב"],
    ["Pet", "Pest", "חיית מחמד", "מזיק"],
    ["Bird", "Fish", "ציפור", "דג"],
    ["Horse", "Cow", "סוס", "פרה"],
    ["Shark", "Dolphin", "כריש", "דולפין"],
    ["Lion", "Lamb", "אריה", "טלה"],
    ["Eagle", "Owl", "נשר", "ינשוף"],
    ["Bee", "Butterfly", "דבורה", "פרפר"],
    ["Frog", "Snake", "צפרדע", "נחש"],
    ["Hamster", "Iguana", "אוגר", "איגואנה"],
    ["Puppy", "Kitten", "גור כלבים", "חתלתול"],
    ["Zoo", "Safari", "גן חיות", "ספארי"],
    ["Domestic", "Feral", "מבוית", "פרוע"],
    ["Cute", "Creepy", "חמוד", "מעורר חלחלה"],
    ["Herd", "Predator", "עדר", "טורף"],
    ["Carnivore", "Herbivore", "אוכל בשר", "אוכל צמחים"],
    ["Mammal", "Reptile", "יונק", "זוחל"],
    ["Nocturnal", "Diurnal", "לילי", "יומי"],
    ["Endangered", "Invasive", "בסכנת הכחדה", "פולש"],
    ["Fur", "Feathers", "פרווה", "נוצות"],
    ["Sloth", "Cheetah", "עצלן", "ברדלס"],
    ["Elephant", "Mouse", "פיל", "עכבר"],
    ["Whale", "Plankton", "לווייתן", "פלנקטון"],
    ["Chirp", "Roar", "ציוץ", "שאגה"],
    ["Ant", "Wasp", "נמלה", "צרעה"],
    ["Goldfish", "Piranha", "דג זהב", "פיראניה"],
    ["Turtle", "Rabbit", "צב", "ארנב"],
    ["Parrot", "Penguin", "תוכי", "פינגווין"],
    ["Spider", "Ladybug", "עכביש", "מושית"],
    ["Goat", "Sheep", "עז", "כבשה"],
  ]),
  "People & Society": cat("People & Society", "אנשים וחברה", [
    ["Hero", "Villain", "גיבור", "נבל"],
    ["Childhood", "Adulthood", "ילדות", "בגרות"],
    ["Introvert", "Extrovert", "מופנם", "מוחצן"],
    ["Parent", "Friend", "הורה", "חבר"],
    ["Teacher", "Student", "מורה", "תלמיד"],
    ["Boss", "Colleague", "בוס", "עמית"],
    ["Best friend", "Acquaintance", "החבר הכי טוב", "מכר"],
    ["Stranger", "Neighbor", "זר", "שכן"],
    ["Old friend", "New friend", "חבר ותיק", "חבר חדש"],
    ["Sibling", "Only child", "אחים", "ילד יחיד"],
    ["Grandparent", "Grandchild", "סבים", "נכדים"],
    ["Mentor", "Peer", "מנטור", "עמית"],
    ["Leader", "Follower", "מנהיג", "מובל"],
    ["Family", "Friends", "משפחה", "חברים"],
    ["Dates", "Marriage", "דייטים", "נישואים"],
    ["Crush", "Partner", "קראש", "בן זוג"],
    ["Listener", "Talker", "מקשיב", "מדבר"],
    ["Optimist", "Realist", "אופטימיסט", "ריאליסט"],
    ["Planner", "Improviser", "מתכנן", "מאלתר"],
    ["Rule-follower", "Rebel", "שומר חוק", "מורד"],
    ["Public speaker", "Wallflower", "נואם", "שתקן"],
    ["Artist", "Engineer", "אמן", "מהנדס"],
    ["Doctor", "Scientist", "רופא", "מדען"],
    ["Politician", "Activist", "פוליטיקאי", "פעיל"],
    ["Athlete", "Scholar", "ספורטאי", "איש אקדמיה"],
    ["Chef", "Food critic", "שף", "מבקר אוכל"],
    ["Giver", "Taker", "נותן", "לוקח"],
    ["Early bird", "Night owl", "אדם של בוקר", "איש לילה"],
    ["Beach person", "Mountain person", "איש חוף", "איש הרים"],
    ["Generation Z", "Baby boomer", "דור Z", "בומרים"],
  ]),
  "Technology": cat("Technology", "טכנולוגיה", [
    ["Phone call", "Text", "שיחת טלפון", "הודעת טקסט"],
    ["Manual", "Automatic", "ידני", "אוטומטי"],
    ["Digital", "Analog", "דיגיטלי", "אנלוגי"],
    ["Real", "Fake", "אמיתי", "מזויף"],
    ["Public", "Private", "ציבורי", "פרטי"],
    ["Facts", "Opinions", "עובדות", "דעות"],
    ["Vintage", "Modern", "וינטג'", "מודרני"],
    ["Online", "Offline", "אונליין", "אופליין"],
    ["Email", "Handwritten letter", "מייל", "מכתב בכתב יד"],
    ["Streaming", "Physical media", "סטרימינג", "מדיה פיזית"],
    ["Laptop", "Desktop", "לפטופ", "מחשב שולחני"],
    ["Smartphone", "Landline", "סמארטפון", "טלפון קווי"],
    ["Password", "Fingerprint", "סיסמה", "טביעת אצבע"],
    ["Cloud", "Local storage", "ענן", "אחסון מקומי"],
    ["Free", "Paid", "חינם", "בתשלום"],
    ["Subscription", "One-time purchase", "מנוי", "רכישה חד פעמית"],
    ["Ads", "No ads", "פרסומות", "בלי פרסומות"],
    ["News", "Gossip", "חדשות", "רכילות"],
    ["Truth", "Misinformation", "אמת", "מידע שגוי"],
    ["Privacy", "Convenience", "פרטיות", "נוחות"],
    ["Work", "Play", "עבודה", "משחק"],
    ["Remote", "Office", "מרחוק", "משרד"],
    ["Startup", "Corporation", "סטארטאפ", "תאגיד"],
    ["Robot", "Human", "רובוט", "אדם"],
    ["A.I.", "Human brain", "בינה מלאכותית", "מוח אנושי"],
    ["Crowded", "Empty", "צפוף", "ריק"],
    ["Old", "New", "ישן", "חדש"],
    ["Smart", "Dumb", "חכם", "טיפש"],
    ["Wired", "Wireless", "עם חוט", "אלחוטי"],
    ["Natural", "Artificial", "טבעי", "מלאכותי"],
  ]),
  "Arts & Entertainment": cat("Arts & Entertainment", "אומנות ובידור", [
    ["Book", "Movie", "ספר", "סרט"],
    ["Funny", "Serious", "מצחיק", "רציני"],
    ["Pop", "Indie", "פופ", "אינדי"],
    ["Comedy", "Drama", "קומדיה", "דרמה"],
    ["Action", "Romance", "אקשן", "רומנטיקה"],
    ["Superhero", "Noir", "גיבור על", "נואר"],
    ["Series", "Film", "סדרה", "קולנוע"],
    ["Live", "Recorded", "חי", "מוקלט"],
    ["Concert", "Festival", "הופעה", "פסטיבל"],
    ["Guitar", "Piano", "גיטרה", "פסנתר"],
    ["Vocals", "Instrumental", "שירה", "אינסטרומנטלי"],
    ["Lyrics", "Melody", "מילים", "מנגינה"],
    ["Classical", "EDM", "קלאסית", "EDM"],
    ["Jazz", "Rock", "ג'אז", "רוק"],
    ["Rap", "Country", "ראפ", "קאנטרי"],
    ["Painting", "Sculpture", "ציור", "פיסול"],
    ["Photo", "Painting", "צילום", "ציור"],
    ["Gallery", "Museum", "גלריה", "מוזיאון"],
    ["Stage", "Screen", "במה", "מסך"],
    ["Improv", "Scripted", "אלתור", "לפי תסריט"],
    ["Plot", "Characters", "עלילה", "דמויות"],
    ["Horror", "Fantasy", "אימה", "פנטזיה"],
    ["Animated", "Live-action", "אנימציה", "לייב אקשן"],
    ["Subtitles", "Dubbing", "כתוביות", "דיבוב"],
    ["eBook", "Paperback", "ספר אלקטרוני", "כריכה רכה"],
    ["Fiction", "Non-fiction", "בדיוני", "עיוני"],
    ["Short story", "Novel", "סיפור קצר", "רומן"],
    ["Movie theater", "Home theater", "קולנוע", "הום סינמה"],
    ["Soundtrack", "Score", "פסקול", "לחן"],
    ["Campfire song", "Stadium anthem", "שיר מדורה", "המנון אצטדיון"],
  ]),
  "Lifestyle & Routine": cat("Lifestyle & Routine", "שגרת חיים", [
    ["Shower", "Bath", "מקלחת", "אמבטיה"],
    ["Morning", "Night", "בוקר", "לילה"],
    ["Early", "Late", "מוקדם", "מאוחר"],
    ["Thrifty", "Lavish", "חסכן", "פזרן"],
    ["Casual", "Formal", "קז'ואל", "רשמי"],
    ["Fast", "Slow", "מהיר", "איטי"],
    ["Routine", "Spontaneity", "שגרה", "ספונטניות"],
    ["Weekday", "Weekend", "חול", "סוף שבוע"],
    ["Homebody", "Adventurer", "אוהב בית", "הרפתקן"],
    ["Tidy", "Messy", "מסודר", "מבולגן"],
    ["Minimalist", "Maximalist", "מינימליסט", "מקסימליסט"],
    ["Apartment", "House", "דירה", "בית"],
    ["Dine out", "Eat in", "אוכלים בחוץ", "אוכלים בבית"],
    ["Running", "Walking", "ריצה", "הליכה"],
    ["Gym", "Yoga", "חדר כושר", "יוגה"],
    ["Marathon", "Sprint", "מרתון", "ספרינט"],
    ["Car", "Bicycle", "מכונית", "אופניים"],
    ["Train", "Plane", "רכבת", "מטוס"],
    ["Road trip", "Flight", "טיול כביש", "טיסה"],
    ["Camping", "Hotel", "קמפינג", "מלון"],
    ["Airbnb", "Resort", "איירבנב", "נופשון"],
    ["Staycation", "Vacation", "נופש ביתי", "חופשה"],
    ["Shopping", "Browsing", "קניות", "גלישה"],
    ["Café", "Home office", "בית קפה", "משרד ביתי"],
    ["Quiet night", "House party", "ערב שקט", "מסיבה ביתית"],
    ["Movie night", "Night out", "ערב סרטים", "ערב בחוץ"],
    ["Reuse", "Discard", "שימוש חוזר", "לזרוק"],
    ["Electric", "Gas car", "מכונית חשמלית", "מכונית בנזין"],
    ["Sleep in", "Power nap", "לישון עד מאוחר", "תנומה"],
    ["Planner app", "Paper calendar", "אפליקציית תכנון", "לוח שנה מנייר"],
  ]),
  "Abstract & Philosophy": cat("Abstract & Philosophy", "מופשט ופילוסופיה", [
    ["Cheap", "Expensive", "זול", "יקר"],
    ["Simple", "Complex", "פשוט", "מורכב"],
    ["Safe", "Dangerous", "בטוח", "מסוכן"],
    ["Order", "Chaos", "סדר", "כאוס"],
    ["Luck", "Skill", "מזל", "מיומנות"],
    ["Instinct", "Logic", "אינסטינקט", "היגיון"],
    ["Soft", "Hard", "רך", "קשה"],
    ["Big", "Small", "גדול", "קטן"],
    ["Normal", "Weird", "נורמלי", "מוזר"],
    ["Certainty", "Ambiguity", "ודאות", "אי בהירות"],
    ["Reason", "Emotion", "היגיון", "רגש"],
    ["Justice", "Mercy", "צדק", "חמלה"],
    ["Freedom", "Security", "חופש", "ביטחון"],
    ["Theory", "Practice", "תיאוריה", "מעשה"],
    ["Abstract", "Concrete", "מופשט", "קונקרטי"],
    ["Nature", "Nurture", "טבע", "חינוך"],
    ["Free will", "Destiny", "רצון חופשי", "גורל"],
    ["Chance", "Choice", "מקרה", "בחירה"],
    ["Quantity", "Quality", "כמות", "איכות"],
    ["Means", "Ends", "אמצעים", "מטרות"],
    ["Style", "Substance", "סגנון", "מהות"],
    ["Form", "Function", "צורה", "תפקוד"],
    ["Beautiful", "Ugly", "יפה", "מכוער"],
    ["Good", "Evil", "טוב", "רע"],
    ["Right", "Wrong", "נכון", "לא נכון"],
    ["Beginning", "End", "התחלה", "סוף"],
    ["Cause", "Effect", "סיבה", "תוצאה"],
    ["Problem", "Solution", "בעיה", "פתרון"],
    ["Question", "Answer", "שאלה", "תשובה"],
    ["Perfect", "Imperfect", "מושלם", "לא מושלם"],
  ]),
};

export const CATEGORIES: string[] = Object.keys(SPECTRA_BY_CATEGORY);

export const CATEGORY_HE: Record<string, string> = Object.fromEntries(
  Object.values(SPECTRA_BY_CATEGORY).map((pairs) => [pairs[0].category, pairs[0].categoryHe]),
);

export const SPECTRA: SpectrumPair[] = Object.values(SPECTRA_BY_CATEGORY).flat();