export interface SpectrumPair {
  left: string;
  right: string;
  category: string;
}

const cat = (category: string, pairs: Array<[string, string]>): SpectrumPair[] =>
  pairs.map(([left, right]) => ({ left, right, category }));

export const SPECTRA_BY_CATEGORY: Record<string, SpectrumPair[]> = {
  "Emotions": cat("Emotions", [
    ["Happy", "Sad"],
    ["Love", "Hate"],
    ["Hope", "Fear"],
    ["Calm", "Anxious"],
    ["Proud", "Shameful"],
    ["Trust", "Doubt"],
    ["Rushed", "Relaxed"],
    ["Boring", "Exciting"],
    ["Nice", "Mean"],
    ["Cute", "Scary"],
    ["Joyful", "Melancholic"],
    ["Confident", "Insecure"],
    ["Brave", "Cowardly"],
    ["Curious", "Apathetic"],
    ["Optimistic", "Pessimistic"],
    ["Grateful", "Entitled"],
    ["Patient", "Impatient"],
    ["Gentle", "Harsh"],
    ["Tender", "Tough"],
    ["Warm", "Distant"],
    ["Empathetic", "Detached"],
    ["Passionate", "Indifferent"],
    ["Innocent", "Cynical"],
    ["Nostalgic", "Forward-looking"],
    ["Stressed", "Carefree"],
    ["Frantic", "Zen"],
    ["Lonely", "Connected"],
    ["Moody", "Even-tempered"],
    ["Ecstatic", "Gloomy"],
    ["Reckless", "Cautious"],
  ]),
  "Food & Drink": cat("Food & Drink", [
    ["Sweet", "Sour"],
    ["Healthy", "Junk"],
    ["Pizza", "Sushi"],
    ["Tea", "Coffee"],
    ["Salty", "Spicy"],
    ["Fresh", "Processed"],
    ["Homemade", "Takeout"],
    ["Soda", "Water"],
    ["Dessert", "Appetizer"],
    ["Wine", "Beer"],
    ["Croissant", "Bagel"],
    ["Burger", "Salad"],
    ["Chocolate", "Fruit"],
    ["Pancakes", "Omelette"],
    ["Creamy", "Crunchy"],
    ["Comfort food", "Fine dining"],
    ["Street food", "Restaurant"],
    ["Cooking", "Baking"],
    ["Grilled", "Fried"],
    ["Whole milk", "Skim milk"],
    ["Bacon", "Tofu"],
    ["Ice cream", "Frozen yogurt"],
    ["Sushi", "Burrito"],
    ["Soup", "Sandwich"],
    ["Popcorn", "Nachos"],
    ["Mint", "Cinnamon"],
    ["Ketchup", "Mustard"],
    ["Rice", "Pasta"],
    ["Smoothie", "Milkshake"],
    ["Brunch", "Midnight snack"],
  ]),
  "Nature & Weather": cat("Nature & Weather", [
    ["Hot", "Cold"],
    ["Light", "Dark"],
    ["City", "Countryside"],
    ["Summer", "Winter"],
    ["Beach", "Mountains"],
    ["Water", "Land"],
    ["Inside", "Outside"],
    ["Wet", "Dry"],
    ["Rural", "Urban"],
    ["Loud", "Quiet"],
    ["Silence", "Noise"],
    ["Ocean", "Desert"],
    ["Forest", "Meadow"],
    ["Sunrise", "Sunset"],
    ["Thunder", "Breeze"],
    ["Snow", "Rain"],
    ["Fire", "Ice"],
    ["Spring", "Autumn"],
    ["River", "Lake"],
    ["Jungle", "Tundra"],
    ["Storm", "Clear sky"],
    ["Volcano", "Glacier"],
    ["Wild", "Tame"],
    ["Island", "Coast"],
    ["Cave", "Mountain peak"],
    ["Shade", "Sunlight"],
    ["Polluted", "Pristine"],
    ["Lakeside", "Waterfall"],
    ["Garden", "Wilderness"],
    ["Tropical", "Arctic"],
  ]),
  "Animals": cat("Animals", [
    ["Cat", "Dog"],
    ["Pet", "Pest"],
    ["Bird", "Fish"],
    ["Horse", "Cow"],
    ["Shark", "Dolphin"],
    ["Lion", "Lamb"],
    ["Eagle", "Owl"],
    ["Bee", "Butterfly"],
    ["Frog", "Snake"],
    ["Hamster", "Iguana"],
    ["Puppy", "Kitten"],
    ["Zoo", "Safari"],
    ["Domestic", "Feral"],
    ["Cute", "Creepy"],
    ["Herd", "Predator"],
    ["Carnivore", "Herbivore"],
    ["Mammal", "Reptile"],
    ["Nocturnal", "Diurnal"],
    ["Endangered", "Invasive"],
    ["Fur", "Feathers"],
    ["Sloth", "Cheetah"],
    ["Elephant", "Mouse"],
    ["Whale", "Plankton"],
    ["Chirp", "Roar"],
    ["Ant", "Wasp"],
    ["Goldfish", "Piranha"],
    ["Turtle", "Rabbit"],
    ["Parrot", "Penguin"],
    ["Spider", "Ladybug"],
    ["Goat", "Sheep"],
  ]),
  "People & Society": cat("People & Society", [
    ["Hero", "Villain"],
    ["Childhood", "Adulthood"],
    ["Introvert", "Extrovert"],
    ["Parent", "Friend"],
    ["Teacher", "Student"],
    ["Boss", "Colleague"],
    ["Best friend", "Acquaintance"],
    ["Stranger", "Neighbor"],
    ["Old friend", "New friend"],
    ["Sibling", "Only child"],
    ["Grandparent", "Grandchild"],
    ["Mentor", "Peer"],
    ["Leader", "Follower"],
    ["Family", "Friends"],
    ["Dates", "Marriage"],
    ["Crush", "Partner"],
    ["Listener", "Talker"],
    ["Optimist", "Realist"],
    ["Planner", "Improviser"],
    ["Rule-follower", "Rebel"],
    ["Public speaker", "Wallflower"],
    ["Artist", "Engineer"],
    ["Doctor", "Scientist"],
    ["Politician", "Activist"],
    ["Athlete", "Scholar"],
    ["Chef", "Food critic"],
    ["Giver", "Taker"],
    ["Early bird", "Night owl"],
    ["Beach person", "Mountain person"],
    ["Generation Z", "Baby boomer"],
  ]),
  "Technology": cat("Technology", [
    ["Phone call", "Text"],
    ["Manual", "Automatic"],
    ["Digital", "Analog"],
    ["Real", "Fake"],
    ["Public", "Private"],
    ["Facts", "Opinions"],
    ["Vintage", "Modern"],
    ["Online", "Offline"],
    ["Email", "Handwritten letter"],
    ["Streaming", "Physical media"],
    ["Laptop", "Desktop"],
    ["Smartphone", "Landline"],
    ["Password", "Fingerprint"],
    ["Cloud", "Local storage"],
    ["Free", "Paid"],
    ["Subscription", "One-time purchase"],
    ["Ads", "No ads"],
    ["News", "Gossip"],
    ["Truth", "Misinformation"],
    ["Privacy", "Convenience"],
    ["Work", "Play"],
    ["Remote", "Office"],
    ["Startup", "Corporation"],
    ["Robot", "Human"],
    ["A.I.", "Human brain"],
    ["Crowded", "Empty"],
    ["Old", "New"],
    ["Smart", "Dumb"],
    ["Wired", "Wireless"],
    ["Natural", "Artificial"],
  ]),
  "Arts & Entertainment": cat("Arts & Entertainment", [
    ["Book", "Movie"],
    ["Funny", "Serious"],
    ["Pop", "Indie"],
    ["Comedy", "Drama"],
    ["Action", "Romance"],
    ["Superhero", "Noir"],
    ["Series", "Film"],
    ["Live", "Recorded"],
    ["Concert", "Festival"],
    ["Guitar", "Piano"],
    ["Vocals", "Instrumental"],
    ["Lyrics", "Melody"],
    ["Classical", "EDM"],
    ["Jazz", "Rock"],
    ["Rap", "Country"],
    ["Painting", "Sculpture"],
    ["Photo", "Painting"],
    ["Gallery", "Museum"],
    ["Stage", "Screen"],
    ["Improv", "Scripted"],
    ["Plot", "Characters"],
    ["Horror", "Fantasy"],
    ["Animated", "Live-action"],
    ["Subtitles", "Dubbing"],
    ["eBook", "Paperback"],
    ["Fiction", "Non-fiction"],
    ["Short story", "Novel"],
    ["Movie theater", "Home theater"],
    ["Soundtrack", "Score"],
    ["Campfire song", "Stadium anthem"],
  ]),
  "Lifestyle & Routine": cat("Lifestyle & Routine", [
    ["Shower", "Bath"],
    ["Morning", "Night"],
    ["Early", "Late"],
    ["Thrifty", "Lavish"],
    ["Casual", "Formal"],
    ["Fast", "Slow"],
    ["Routine", "Spontaneity"],
    ["Weekday", "Weekend"],
    ["Homebody", "Adventurer"],
    ["Tidy", "Messy"],
    ["Minimalist", "Maximalist"],
    ["Apartment", "House"],
    ["Dine out", "Eat in"],
    ["Running", "Walking"],
    ["Gym", "Yoga"],
    ["Marathon", "Sprint"],
    ["Car", "Bicycle"],
    ["Train", "Plane"],
    ["Road trip", "Flight"],
    ["Camping", "Hotel"],
    ["Airbnb", "Resort"],
    ["Staycation", "Vacation"],
    ["Shopping", "Browsing"],
    ["Café", "Home office"],
    ["Quiet night", "House party"],
    ["Movie night", "Night out"],
    ["Reuse", "Discard"],
    ["Electric", "Gas car"],
    ["Sleep in", "Power nap"],
    ["Planner app", "Paper calendar"],
  ]),
  "Abstract & Philosophy": cat("Abstract & Philosophy", [
    ["Cheap", "Expensive"],
    ["Simple", "Complex"],
    ["Safe", "Dangerous"],
    ["Order", "Chaos"],
    ["Luck", "Skill"],
    ["Instinct", "Logic"],
    ["Soft", "Hard"],
    ["Big", "Small"],
    ["Normal", "Weird"],
    ["Certainty", "Ambiguity"],
    ["Reason", "Emotion"],
    ["Justice", "Mercy"],
    ["Freedom", "Security"],
    ["Theory", "Practice"],
    ["Abstract", "Concrete"],
    ["Nature", "Nurture"],
    ["Free will", "Destiny"],
    ["Chance", "Choice"],
    ["Quantity", "Quality"],
    ["Means", "Ends"],
    ["Style", "Substance"],
    ["Form", "Function"],
    ["Beautiful", "Ugly"],
    ["Good", "Evil"],
    ["Right", "Wrong"],
    ["Beginning", "End"],
    ["Cause", "Effect"],
    ["Problem", "Solution"],
    ["Question", "Answer"],
    ["Perfect", "Imperfect"],
  ]),
};

export const CATEGORIES: string[] = Object.keys(SPECTRA_BY_CATEGORY);

export const SPECTRA: SpectrumPair[] = Object.values(SPECTRA_BY_CATEGORY).flat();
